### ISSUE TITLE
Minor type in description of Antigravity Projection power

### ISSUE THREAD

**Issue by mark-truran** [Labernator/Stargrave#6]
Hi,

I spotted this when my friends played a few games last week. 

The text description for this power has 'Leviathan' but it should be 'Levitate'. 

![image](https://user-images.githubusercontent.com/13332188/201498699-10e255b0-7e77-4948-937f-156eb3f9f14e.png)

Kind regards,

Mark

**Comment by Labernator** [comment]
Hi Mark, 
sorry for the slow response on this.
Changed it and redeployed.
Best regards,
Marius

**Comment by mark-truran** [comment]
Hi Marius,

No problem. I didn't know if you wanted to hear about small things like this :) 

Everything else is flawless.

Mark

**Comment by Labernator** [comment]
> Hi Marius,
> 
> No problem. I didn't know if you wanted to hear about small things like this :) 
> 
> Everything else is flawless.
> 
> Mark
> 

Hi Mark,

Totally appreciate every bit of feedback, be it as small as this or as big as a feature request for a desktop app ;)

Marius
