### ISSUE TITLE
Desktop friendly version of app

### ISSUE THREAD

**Issue by mark-truran** [Labernator/Stargrave#7]
Hi Marius,

I wondered if you were planning to created a desktop friendly version of this app. At the moment, when I open the configurator on my PC I see a malformed screen.

![malformed](https://user-images.githubusercontent.com/13332188/202899813-57d57508-e714-4c77-8ae6-4157f2805f24.png)

I fix this by using the developer tools to spoof a mobile phone, and then everything looks great. This workaround is fine for me but confuses some of my friends. 

For desktop users, would be possible to emulate the developer tools i.e. show a representation of a phone, centred on the screen?

![devtools](https://user-images.githubusercontent.com/13332188/202899845-5ad50187-a919-4b05-aa41-2868de21c91a.png)

This might prevent false reports that the site is broken, when it is not.

Mark

**Comment by Labernator** [comment]
Hi Mark,

I wanted to have a desktop version of this for a while now.
Desktop would simplify a lot of things that I had to work around for my mobile centric gaming group.

I'll see how I can solve this with little effort for now and once I got some spare time I will work on something more sophisticated for desktop users.

**Comment by Labernator** [comment]
Hi Mark,

i just uploaded the easy fix to limit the desktop to a smaller screen, so it should not look distorted anymore.
A real desktop app will come some day in the future.

Best regards,
Marius

**Comment by mark-truran** [comment]
Brilliant. That's much better than switching on dev tools. 

A real desktop app would be great.
