### ISSUE TITLE
Missing backgrounds - Fatewinder and Investigator

### ISSUE THREAD

**Issue by mark-truran** [Labernator/Stargrave#8]
Hi Marius,

I notice that the app does not have the new backgrounds introduced in 'The Last Prospector' - the Fatewinder and the Investigator. And I think there may be some soldiers and powers missing. Are you planning to add these at some point? 

If I can help in any way let me know. I use a different tech stack to you (Angular, C#, Sql server) but I can edit data files etc. And I am just about to buy the expansion books.

Kind regards,

Mark

**Comment by Labernator** [comment]
Hi Mark,

I do not own the Prospector book as of yet, so I do not have it at hand to put into the json files that this app uses.
All files are stored here:
https://github.com/Labernator/Stargrave/tree/main/src/data
There is one for character backgrounds, one for soldiers and one for powers.
If you can provide the missing data, I can add it

**Comment by mark-truran** [comment]
I'm happy to do that. I will get the book and send you the missing data.

**Comment by mark-truran** [comment]
Here are the new Powers. I can't add a JSON file here for some reason, so I have had to ZIP it.

[Powers.zip](https://github.com/Labernator/Stargrave/files/10186102/Powers.zip)

**Comment by mark-truran** [comment]
Here are the 4 new soldiers. It looks like a mistake but the Striker is supposed to have 2 hand weapons. 

All of the new soldiers have attributes e.g. the Engineer has 'Ship Cost Discount' which reduces ship upgrade costs by 20%. I can't see a place for that information in your JSON. Could you add an 'Attributes' property? Or 'Notes'? Just an idea.

[Soldiers.zip](https://github.com/Labernator/Stargrave/files/10186296/Soldiers.zip)

**Comment by mark-truran** [comment]
Ship upgrades

[ShipUpgrades.zip](https://github.com/Labernator/Stargrave/files/10195166/ShipUpgrades.zip)

**Comment by mark-truran** [comment]
**Backgrounds**

These are a little different to the other backgrounds in Stargrave.

The INVESTIGATOR has no mandatory stat modifications. Their optional stat modifications are [+2 will, +2 health, +1 move, +1 fight, +1 shoot] (pick any two modifications).

The FATEWINDER has optional stat modification that are in two blocks. You must pick from [+1 Will OR +1 Health] AND [+1 Move, +1 Fight, +1 Shoot] .  

[Backgrounds.zip](https://github.com/Labernator/Stargrave/files/10195391/Backgrounds.zip)

**Comment by mark-truran** [comment]
Critters

[Critters.zip](https://github.com/Labernator/Stargrave/files/10200192/Critters.zip)

**Comment by mark-truran** [comment]
Gear. I set the 'list' property to 3 to distinguish them from the original advanced technology items.

[Gear.zip](https://github.com/Labernator/Stargrave/files/10249634/Gear.zip)
